version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
    - "mysql_data:/var/lib/mysql:delegated"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - "${MYSQL_PORT}:3306"
    expose:
    - 3306
    restart: unless-stopped

volumes:
  mysql_data: